### PR TITLE
Ability to create VMs locally

### PR DESCRIPTION
**Pull request by diegorusso**
Guys,

I've changed a lot the vmcreator. The code has the following changes:
- the main feature is the ability to create VMs independently from your website: the only need is a JSON file that describes the game.
- code has been divided in modules
- PEP8!
- Logging has been improved to log both in the console (less verbose) and in a file
- update README to set up the environment
- guestmount/guestumount path from Jacopo

I've created up two VMs (look at example_game.json) and they are working fine: all the service are running both on team VMs and Org VM.
Only one thing I haven't tried: the spawner.py (because I don't know the SECRET). So please test it.
Please review the code and discuss about the changes.

Thanks a lot.

### CODE REVIEW

**Comment by zardus** [comment]
Hi Diego,

I was assigned to get this merged. We have a huge deadline coming up on the 23rd, but I will get to this right after that!

**Comment by diegorusso** [comment]
Yan, don't worry. Take your time.

--
Diego Russo
Staff Software Engineer - diego.russo@arm.com
Direct Tel. no: +44 1223 405920
Main Tel. no: +44 1223 400400
ARM Ltd. CPC1, Capital Park, Cambridge Road, Fulbourn, CB21 5XE, United
Kingdom
http://www.diegor.co.uk - http://twitter.com/diegor
http://www.linkedin.com/in/diegor

2015-02-14 7:53 GMT+00:00 Yan <notifications@github.com>:

**Comment by zardus** [comment]
Hi Diego,

Just to keep you in the loop, I'm finally checking this out. Sorry about the delay; the runup to the iCTF has been crazy :-).

**Comment by diegorusso** [comment]
@zardus all right, don't worry. Let me know.

**Comment by thuanbv2203** [comment]
Link http://ictf.cs.ucsb.edu/base-vms/base-vms.tar.gz has been died.
Please help me!!!

**Pull request closed without merging**
